language: python
sudo: required
dist: xenial
python: '3.7'
script: 'python build.py'
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist/photon-icons.svg"
  skip_cleanup: true
  on:
    tags: true
